# ============================================================
#   ZV-Manager - Global Configuration
# ============================================================

# Commit hash — diisi otomatis saat install/update, jangan diubah manual
COMMIT_HASH=""
