# ============================================================
#   ZV-Manager - Global Configuration
# ============================================================

# --- Port SSH ---
SSH_PORT=22
SSH_PORT_2=500
SSH_PORT_3=40000

# --- Port Dropbear ---
DROPBEAR_PORT=109
DROPBEAR_PORT_2=143

# --- Port WebSocket ---
WS_PORT=80
WSS_PORT=443

# --- Port UDP Custom (internal listener) ---
UDP_PORT=36712

# --- Port Nginx info page ---
NGINX_PORT=81

# --- Commit hash — diisi otomatis saat install/update, jangan diubah manual ---
COMMIT_HASH=""
